### ISSUE TITLE
Make it work on 27Mhz

### ISSUE THREAD

**Issue by sandmix** [dimhoff/sensof#1]
On main page I didn't find the frequency this device should work and if it's configurable can it work on 27Mhz ?

**Comment by dimhoff** [comment]
No it doesn't and will never work on 27 MHz.

**Comment by sandmix** [comment]
SI4010  frequency rande 27–960 MHz why it can't be used on 27Mhz.

**Comment by dimhoff** [comment]
Apparte from any physical hardware limitations, because its not in the scope of this project.

If you really want the have Sensof sensors on 27 MHz. Then please send my your contact details so I can prepare a quote on how much development would cost you.
